//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public OrderDetails()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int DetailsId { get; set; }
        public Nullable<decimal> CustomerPrice { get; set; }
        public int Quantity { get; set; }
        public int OrdersOrderId { get; set; }
    
        public virtual Orders Order { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
